In [175]:
from pathlib import Path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import StrMethodFormatter
import seaborn as sns
import sqlite3


# SQLite database
conn = sqlite3.connect("../crimedatacsv_new.db")

print("Connected")

Connected

Creating a subset for query and visuals...

In [176]:
import os
print(os.getcwd())

c:\Users\bperf\OneDrive\Desktop\UBIAnalysis\notebooks

In [177]:
import os

print(os.path.exists("../crimedatacsv_new.db"))

True

In [178]:
pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table';
""", conn)

          name
0     la_crime
1  local_crime
2   cps_income
3   ubi_subset

In [179]:
pd.read_sql("""
select *
from cps_income
""", conn)

,YEAR,REGION,STATEFIP,COUNTY,METRO,ASECWT,AGE,SEX,RACE,OCC,UHRSWORK1,EDUC,SCHLCOLL,INCWAGE,OFFTOTVAL,POVERTY
0,2024,33,48,0,2,1898.77,80,1,100,0,999,40,0,0,91488,23
1,2024,31,13,0,3,3187.62,64,2,100,800,40,111,0,161000,294060,23
2,2024,12,36,0,4,2597.91,17,2,100,0,999,60,1,0,55002,23
3,2024,21,17,17119,3,1810.53,25,2,100,0,999,111,5,30000,43201,21
4,2024,31,37,37001,4,11338.34,45,1,100,6600,45,71,5,55000,65000,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,2024,21,55,0,3,2963.89,35,1,100,220,40,73,5,100000,190006,23
1496,2024,12,36,36103,3,2398.32,31,1,100,6410,997,73,5,70000,70115,23
1497,2024,32,28,0,3,1858.24,50,2,200,2310,40,111,5,36000,38500,23
1498,2024,31,12,12099,3,2363.39,85,2,100,4230,997,73,0,40000,130378,23
1499,2024,31,12,12083,4,4550.81,14,2,200,0,999,1,0,99999999,26000,10

In [180]:
#occupation codebook normalization

occ_input = "../data/occ_codebook.txt"
occ_output = "../data/occ_codebook_normalized.txt"

with open(occ_input, "r", encoding="utf-8") as infile:
    lines = [line.strip() for line in infile if line.strip()]

# Remove header
if not lines[0].isdigit():
    lines = lines[1:]

normalized = []

for i in range(0, len(lines), 2):
    code = lines[i]
    description = lines[i + 1]

    # Check if code is a range (example: 010–014)
    if "–" in code:
        start, end = code.split("–")

        for num in range(int(start), int(end) + 1):
            normalized.append(f"{num:03d}")
            normalized.append(description)

    # Single code
    else:
        normalized.append(code)
        normalized.append(description)


# Write the new normalized file
with open(occ_output, "w", encoding="utf-8") as outfile:
    for line in normalized:
        outfile.write(line + "\n")

print("Normalized occupation codebook created!")


educ_input = "../data/educ_codebook.txt"
educ_output = "../data/educ_codebook_normalized.txt"

with open(educ_input, "r", encoding="utf-8") as infile:
    lines = [line.strip() for line in infile if line.strip()]

# Remove header
if not lines[0].isdigit():
    lines = lines[1:]

normalized = []

for i in range(0, len(lines), 2):
    code = lines[i]
    description = lines[i + 1]

    # Check if code is a range (example: 010–014)
    if "–" in code:
        start, end = code.split("–")

        for num in range(int(start), int(end) + 1):
            normalized.append(f"{num:03d}")
            normalized.append(description)

    # Single code
    else:
        normalized.append(code)
        normalized.append(description)


# Write the new normalized file
with open(educ_output, "w", encoding="utf-8") as outfile:
    for line in normalized:
        outfile.write(line + "\n")

print("Normalized education codebook created!")





#schlcoll_codebook normalization

schlcoll_input = "../data/schlcoll_codebook.txt"
schlcoll_output = "../data/schlcoll_codebook_normalized.txt"

with open(schlcoll_input, "r", encoding="utf-8") as infile:
    lines = [line.strip() for line in infile if line.strip()]

# Remove header
if not lines[0].isdigit():
    lines = lines[1:]

normalized = []

for i in range(0, len(lines), 2):
    code = lines[i]
    description = lines[i + 1]

    # Check if code is a range (example: 010–014)
    if "–" in code:
        start, end = code.split("–")

        for num in range(int(start), int(end) + 1):
            normalized.append(f"{num:03d}")
            normalized.append(description)

    # Single code
    else:
        normalized.append(code)
        normalized.append(description)


# Write the new normalized file
with open(schlcoll_output, "w", encoding="utf-8") as outfile:
    for line in normalized:
        outfile.write(line + "\n")

print("Normalized school and college codebook created!")




# Cleans income data
ubi_subset['INCWAGE'] = ubi_subset['INCWAGE'].replace(99999999, np.nan)

ubi_subset = ubi_subset.dropna(subset=['INCWAGE'])

ubi_subset = ubi_subset[ubi_subset['INCWAGE'] > 0]

pd.read_sql("""
select *
from cps_income
""", conn)

ubi_subset

Normalized occupation codebook created!

IndexError: list index out of range

In [181]:
educ_input = "../data/educ_codebook.txt"

with open(educ_input, "r", encoding="utf-8") as infile:
    lines = infile.readlines()

print("Number of lines:", len(lines))
print(lines[:10])

Number of lines: 0
[]

In [182]:
import os

print(os.path.abspath("../data/educ_codebook.txt"))
print(os.path.exists("../data/educ_codebook.txt"))
print(os.path.getsize("../data/educ_codebook.txt"))

c:\Users\bperf\OneDrive\Desktop\UBIAnalysis\data\educ_codebook.txt
True
0

In [ ]:
from pathlib import Path

print(Path.cwd())

c:\Users\bperf\OneDrive\Desktop\UBIAnalysis\notebooks

In [ ]:
from pathlib import Path

print(Path("occ_codebook.txt").exists())
print(Path("../data/occ_codebook.txt").exists())
print(Path("../occ_codebook.txt").exists())

False
True
False

In [ ]:
# import folium

# m = folium.Map(location=[39,-95], zoom_start=11)

# for _, row in la_crime.iterrows():
#     folium.CircleMarker(
#         [row['LAT'], row['LON']],
#         radius=3,
#         color="red"
#     ).add_to(m)

# m

Correlation Heatmap

Geographic Crime Map

###Produce Polished Visuals That Communicate Your Story:  
Create a small set of polished, high-quality visuals for your Keystone Project. Each visual should include a short markdown explanation addressing:

What question or idea this chart helps answer
Why this chart type is appropriate
What design choices you made (color, labels, order, scale)
How you ensured accuracy and avoided misleading design
This is where your project begins to shift from exploration to communication.###

Universal Basic Income (UBI)- What it means, from one person to next, may vary a little. Here the UBI is described as Income given freely based on happiness; just as what it means may vary, the criteria is a bit shrouded. I on the other hand, sought out indicators, that could predetermine ones happiness.  In the United States, it is believed that certain markers indicate 'having arrived' or 'made it' in society, here I have listed education-highschool and college, income, age, sex, race, and occupation. The fields I have chosen as indicators, also, have a history of disparages.

a flow chart Income - Expendiutures = Discretionary/non-essential Income...If you do the math...

Next then given the disparages what are societal factors, or a factor that can bring down happiness, even after having arrived. Here I would like to take a look at deviant behaviors that could cause a break a rift, a decline in society, causing unhappiness. One major factor associated with unhappiness outside of the societal norms, could be crime. Crime and its effects and affects on society. Could the the UBI be used to acknowledge the loss = unhappiness to society caused by crime, and head it off?  Could the UBI break the cycles that plague us, generation after generation? Can the UBI provide hope, in a hopless situation, or an even more hopeless, world?

The effects and affects of crime and the community. A chart showing how crime can effect and affect the overall median income in a society, and the possible results if left unchecked, anywhere from upheaval to dissolution of the state.

Again, in conclusion I would like to state that given the disparages of society, that could be argued as the trickle down economics of a domminant or dominant classes and 'scarcity of goods' within society.  Society, cultures, develop natural fissure, due to wear and tear, but the one thing that gets us all, eventually, is time. The only unnatural occuring theme here is crime; and that usually happens due to a lack in vision, I woould argue.